### ISSUE TITLE
creator 版本 10.2 ， AmazingEffect全都跑不起来

### ISSUE THREAD

**Issue by yanjifa** [fylz1125/ShaderDemos#6]
模拟器上什么都没有， 浏览器上看到一个灰色的框， 控制台一直在报错
Uncaught Error: cc.GLProgram.getUniformLocationForName(): Invalid operation. Cannot get uniform location when program is not initialized

**Comment by fylz1125** [comment]
目前只适应1.8,1.9版本，由于1.10开始到2.x整个shader都重做了，所以不能直接用，后续跟进2.x系列，目前没有计划支持1.10的版本
